#!/usr/bin/env bash
while [[ true ]]
do
DIALOG=${DIALOG=dialog}
tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15
$DIALOG --clear --title "Меню" \
        --menu "Выберите скрипт:" 20 70 4 \
        "remtrash"  "Удаляет мусор. Вызывается с $HOME/work" \
        "unftrash" "Восстанавливает мусор. Вызывается с work" \
        "makebackup" "Делает бэкап" \
        "restorebackup" "Восстанавливает из бэкапа" 2> $tempfile
retval=$?
choice=`cat $tempfile`
case $retval in
    0)
        case $choice in
        remtrash) ./remtrash $HOME/work break;;
        unftrash) ./unftrash work break;;
        makebackup) ./makebackup break;;
        restorebackup) ./restorebackup break;;
        esac;;
    1)
        echo "Выбрано 'Нет'."
        exit 1
        clear;;
    255)
        echo "Нажата клавиша ESC."
        exit 1
        break;;
esac
done